# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mochi}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Damian Nurzynski (dnurzynski)"]
  s.date = %q{2010-08-03}
  s.email = %q{dnurzynski@gmail.com}
  s.files = [
    "app/models/mochi/feed.rb",
     "lib/mochi.rb",
     "lib/mochi/engine.rb"
  ]
  s.homepage = %q{http://github.com/dnurzynski/mochi}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Mochi Bridge implementation for Rails3 (www.mochimedia.com)}
  s.test_files = [
    "spec/feed_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<happymapper>, [">= 0"])
    else
      s.add_dependency(%q<happymapper>, [">= 0"])
    end
  else
    s.add_dependency(%q<happymapper>, [">= 0"])
  end
end

